# Generated by Django 3.2.5 on 2021-07-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='-', max_length=255, upload_to='autos')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('combustible', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('tipo_caja', models.CharField(max_length=50)),
                ('aire_acondicionado', models.CharField(max_length=50)),
                ('alzavidrios', models.CharField(max_length=50)),
                ('direccion_hidraulica', models.CharField(max_length=50)),
                ('tranmision_auto', models.CharField(max_length=50)),
                ('espejos', models.CharField(max_length=50)),
                ('radio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
                'db_table': 'autos',
                'ordering': ['id'],
            },
        ),
    ]
